version: "1"
services:
  host_reg:
    build: .
    links:
      - redis
    expose:
      - 8888
    ports:
      - "127.0.0.1:9601+:8888"
    command: --redis-port=6379 --redis-host=redis

  redis:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - /var/lib/redis:/data
